Module2 task1
htmlacademy-ecmascript/151400-cinemaddict-15 pull request #4
Opened 2021-08-07 19:26 UTC by vsevolodroschupkin

- сделал моки данных фильма
- подоговил шаблон карточки
- вывел данные о фильме в попап
- сделал кнопку
- сформировоал на основе моковх о фильмах основное меню

Не сделал
Комментарии в попапе

2021-08-08 10:24 UTC, raccoonlemon requested changes
Как можно сгенерировать комментарии к фильмам:

- Нужно сначала сенерировать список фильмов.

- Обходим список фильмов, и для каждого фильма генерируем комментарии. Айди этих комментариев записываем в поле Commenst для фильма. Сами комментарии помещаем в общий массив комментариев.

- В итоге мы должны получить список фильмов + поле комментарий у каждого фильма (массив id), и полный список всех комментариев.

- Так же мы должны иметь возможность получить список комментариев к фильму. Это можно сделать с помощью методов массива filter и includes. Что-то вроде:

```
const getFilmComments = (film, comments) => {
 const commetnsIds = film.comments;
 return comments.filter(item=>commentsIds.includes(item.id))
}
```

2021-08-08 10:24 UTC, raccoonlemon commented on src/view/profile.js
> +export const createProfileTemplate = (profile) => {
Здесь можем в параметрах оставить только rank (profileTitle).

2021-08-08 10:24 UTC, raccoonlemon commented on src/mock/movie-mock.js
> +dayjs.extend(dayjsRandom);
Чтобы сгенерировать дату выпуска фильма, можно воспользоваться синтаксисом 
new Date(Year, Month, Day) - и туда передать рандомные значения. Год например от 1950 до 2021, месяц 0-11 (т.к они с 0 нумеруются, и дни допустим 1-25.

Чтобы сгенерировать дату комментария можно взять текущую дату и отнять от нее рандомное количество дней. В datejs есть функция по добавлению к дате указанного количества дней.

`dayjs(date).add(daysCount, 'days').toDate()`

2021-08-10 04:07 UTC, vsevolodroschupkin commented on src/const.js
> +export const COMMENT_MIN_QNTY = 0;
Сделал

2021-08-10 04:12 UTC, vsevolodroschupkin commented on src/main.js
> +const TOTAL_MOVIE_NUMBER = 130291;
Сделал,
передал в шаблон длину массива movies

2021-08-10 04:15 UTC, vsevolodroschupkin commented on src/mock/filters-mock.js
> +const moviesToFilterMap = {
Перенес в utils

2021-08-10 04:29 UTC, vsevolodroschupkin commented on src/view/popup.js
> +  const durationHours = Math.floor(filmInfo.runtime / 60) !== 0 ? `${Math.floor(filmInfo.runtime / 60)}h` : '';
вынес в отдельную функцию

2021-08-10 04:36 UTC, vsevolodroschupkin commented on src/view/popup.js
> +  const description = filmInfo.description.length <= MAX_DESCRIPTION_LENGTH ? filmInfo.description : `${filmInfo.description.slice(0, MAX_DESCRIPTION_LENGTH - 1)  }...`;
вынес в отдельную функцию

2021-08-10 04:39 UTC, vsevolodroschupkin commented on src/view/profile.js
> +export const createProfileTemplate = (profile) => {
+

2021-08-10 05:22 UTC, vsevolodroschupkin commented on src/const.js
> +  '0+',
перенес константы в мок файлы
в const оставил только Эмоции и макс длину строки описания.
Они используются  в нескольких местах

2021-08-10 10:36 UTC, merged