Module3 task1
htmlacademy-ecmascript/151400-cinemaddict-15 pull request #5
Opened 2021-08-14 21:39 UTC by vsevolodroschupkin

Переписал все компоненты на классы
Добавил открытие, закрытие окна с деталями о фильме

Вопросы:
— комопнент popup довольно сложный, содержит в себе комментарии. 
Надо ли комментарии тоже переписывать на классы и выносить из popup?

2021-08-15 10:34 UTC, raccoonlemon requested changes
Компонент popup в дальнейшем действительно возможно будет можно и нужно разбить на более мелкие. Но про него еще будет в следующих заданиях, можно пока оставить как есть.

Я смотрю что ты задание 3-2 тоже сделал в этом же пулреквесте. Вот только компонент NoMovie не выводится когда нет фильмов. (можно в следующем задании сделать)

2021-08-15 10:34 UTC, raccoonlemon commented on src/main.js
> +    });
Еще попап должен открываться по щелчку на наименование фильма и комменты, см. ТЗ:
`Клик по обложке фильма, заголовку, количеству комментариев открывает попап с подробной информацией о фильме;`

2021-08-15 10:34 UTC, raccoonlemon commented on src/main.js
> +render(mainElement, new ContentView().getElement(), RenderPosition.BEFOREEND);
Можно бы порефакторить компонент ContentView. Чтобы уже избавиться от nth-child.

Можно добавить в класс дополнительные методы типа "getAllFilmsContainer, getTopRatedContainer, ..." и возвращать по querySelector нужный контейнер.

Или можно этот компонент разбить еще на два. FilmsContainer и FilmsList.
FilmsList должен принимать в конструктор title и признак что это доп. лист, чтобы добавлять при необходимости класс 'films-list--extra'. И в нем метод getContainer, чтобы получить внутренний div куда рендерятся фильмы. Для заголовков списков можно завести общее перечисление.

2021-08-15 10:34 UTC, raccoonlemon commented on src/main.js
> +  document.body.classList.add('hide-overflow');
При закрытии попапа класс hide-overflow нужно удалить.

2021-08-15 10:34 UTC, raccoonlemon commented on src/main.js
> +}
Хитренько.. циклическая зависимость при помощи function declaration между onPopupEscKeydown и closePopup.
Не годится, нужно это исправить =)

При закрытии попапа по esc в консоль падает ошибка:
`Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.`

Объявление обоих функций (onPopupEscKeydown и closePopup) лучше перенести в openPopup. И в removeChild тогда можно передавать popupComponent.getElement().

2021-08-16 18:47 UTC, vsevolodroschupkin commented on src/main.js
> +  document.body.classList.add('hide-overflow');
Удалил

2021-08-16 18:47 UTC, vsevolodroschupkin commented on src/main.js
> +render(mainElement, new ContentView().getElement(), RenderPosition.BEFOREEND);
Постарался пойти по второму пути, но кажется перемудрил.

2021-08-16 18:48 UTC, vsevolodroschupkin commented on src/main.js
> +    });
Ага, сделал.
Подскажи, а как в идеале собирать массив интерактивных элементов карточки или например строки таблицы, если не всяк строка/карточка кликабельные, а частично.

2021-08-16 18:50 UTC, vsevolodroschupkin commented on src/main.js
> +}
Ошибку отловил.
Она была из-за того, что навесил обработчик на esc два раза в коллбеке и в функции закрытия.

2021-08-16 19:32 UTC, vsevolodroschupkin commented on src/main.js
> +}
От цикла постарался избавиться, посмотри пжста, годится ли так.

2021-08-17 06:52 UTC, raccoonlemon commented on src/main.js
> +    });
Как вариант, можно сделать через делегирование.
Твой вариант вполне нормальный. Правда я бы наверное в массив поместила не сами элементы, а просто массив селекторов, и в цикле выбирать нужный элемент. Но тут пожалуй нет какого-то эталонного решения.
![image](https://user-images.githubusercontent.com/71271294/129677732-dd74976d-812b-4e3e-9d45-5c8c2e58bc9b.png)

2021-08-17 06:53 UTC, raccoonlemon commented on src/main.js
> +}
Да, с коллбеком отличное решение.
В следующих заданиях будет возможность еще порефакторить и возможно даже без коллбека сделать.
Но на текущем этапе это хорошее решение.

2021-08-17 07:01 UTC, raccoonlemon commented on src/main.js
> +render(mainElement, new ContentView().getElement(), RenderPosition.BEFOREEND);
Вынести настройки в константу идея хорошая.
Но рендерить их в цикле пожалуй излишне. 
Тут было бы лучше рендерить отдельно типа renderAll, renderTopRated, renderMostCommented. Они вроде то все списки, но логика и внутренности у них немного разные все-таки.

2021-08-17 07:04 UTC, raccoonlemon commented
Заметила еще такой баг в открытии попапа:
- не открывается форма попапа для карточек которые отрисовались по Load More.

И нужно переименовать файл filmslist=>films-list, класс Filmslist=>FilmsList.

Это задание принимаю, поправь, пожалуйста, в следующем.

2021-08-17 07:05 UTC, raccoonlemon approved these changes

2021-08-17 07:06 UTC, merged